### ISSUE TITLE
Award of Microconsulting Work Statement - API Outreach 36C10B18P2715

### ISSUE THREAD

**Issue by mjunda** [department-of-veterans-affairs/VA-Micropurchase-Repo#16]
## Background
The Lighthouse program is moving VA towards an Application Programming Interface (API) first driven digital enterprise, which will establish the next generation open management platform for Veterans and accelerate transformation in VA's core functions, such as Health, Benefits, Burial and Memorials. This platform will be a system for designing, developing, publishing, operating, monitoring, analyzing, iterating and optimizing VA’s API ecosystem.

## The Play
As the Lighthouse Product Owner, I must have a repeatable process to communicate with internal and external stakeholders the availability of existing, new, and future APIs so that the information can be consumed for the benefit of the Veteran.  This outreach/evangelism effort may be different depending on the API type.

## Deliverable
A defined and repeatable strategy/process to evangelize existing, new, and future APIs to VA's stakeholders as products.  This may be in the form of charts, graphics, narrative, or combination thereof.  Ultimately, VA wants the best format to accurately communicate the process/strategy.  This strategy/process may be unique to each type of API.

Deliverable shall be submitted to VA's GitHub Repo. 

## Definition of Done
-  Deliverable that accurately and clearly demonstrates a repeatable strategy/process
-  Submission to GitHub

## Time Box
VA anticipates a 2 week iteration to be sufficient.

## Disclaimer
In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information).  Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network.  Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Purchase Order Clauses
   
- FAR 52.204-13 System for Award Management Maintenance (OCT 2016)
- FAR 52.227-14 Alternate IV Rights in Data—General (DEC 2007)
- FAR 52.232-33 Payment by Electronic Funds Transfer—System for Award Management (JUL 2013)
- FAR 52.232-39 Unenforceability of Unauthorized Obligations (JUN 2013)
- VAAR 852.232-72 Electronic submission of payment requests. (NOV 2012)

**Comment by mjunda** [comment]
Yes, the plan is to post the deliverables in this GitHub repo.

**Comment by JCQuin** [comment]
Deliverables will be placed in this folder: https://github.com/department-of-veterans-affairs/VA-Micropurchase-Repo/tree/master/2018-04-27_API_Outreach
