### ISSUE TITLE
DRAFT - Microconsulting Work Statement – Lighthouse Lab Developer Outreach

### ISSUE THREAD

**Issue by JCQuin** [department-of-veterans-affairs/VA-Micropurchase-Repo#17]
# DRAFT - Microconsulting Work Statement – Lighthouse Lab Developer Outreach

## Background 
VA is looking to expand the adoption of our developer sandbox (Lighthouse Lab).  Simply making datasets and APIs available does not guarantee success.  Developers, Data Scientists and Researchers need to discover, try and ultimately decide to leverage VA data and APIs in the innovations they are building. This requires clear messaging that reaches Developers where they spend their time.  Documentation, demos, webinars, conferences, blog posts and more are used to effectively market to Developers.  

## The Play
As Product Manager I am seeking to meet developers where they are. I would like to better understand, with the intent to implement, best practices from the private and public sector in building documentation, demos, webinars, conferences, and blog posts to market our developer sandbox "Lighthouse Lab." We would like the primary research performed to gather best practices around: 

- Characteristics of effective developer outreach programs similar to Lighthouse Lab, and who is successfully implementing them.

- Lessons learned from these organizations (both what is working and what isn't).
- Interviews with current developers in Lighthouse Lab and potential developers to understand their needs. List of current developers will be provided. 

- Recommendations for a developer outreach strategy VA should adopt for Lighthouse Lab. 

## Deliverable
- Vendor shall make recommendations for an outreach strategy for Lighthouse Lab on best practices learned from the evaluated entities. Data shall be presented to VA in the most appropriate way, as defined in the proposal.

- Vendor shall provide all data/research learned from each entity to build the recommendation.

## Definition of Done
- Deliverable representative of the effort described in vendor's proposal 

- Submission to VA Github as .md file, or other submission as described in proposal.

## Time Box
VA anticipates a 2 week iteration to be sufficient. Vendor may propose alternate time frame for VA's consideration.

## Disclaimer
In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information).  Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network.  Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Evaluation
- Vendor will provide a one-page or less description detailing their ability to deliver.
- Vendor shall provide a fixed price for the entire work effort.  VA's micropurchase authority permits actions up to $10,000.
- Government will determine which proposal is most beneficial to the Government.
- Submissions shall be made to the following email addresses by (Date) 2018.
	 
	Mark.junda@va.gov  
	David.melton@va.gov  

## Solicitation Provisions
- FAR 52.204-7 System for Award Management (OCT 2016)

## Purchase Order Clauses
   
- FAR 52.204-13 System for Award Management Maintenance (OCT 2016)
- FAR 52.227-14 Alternate IV Rights in Data—General (DEC 2007)
- FAR 52.232-33 Payment by Electronic Funds Transfer—System for Award Management (JUL 2013)
- FAR 52.232-39 Unenforceability of Unauthorized Obligations (JUN 2013)
- VAAR 852.232-72 Electronic submission of payment requests. (NOV 2012)

**Comment by cosentino1** [comment]
Hello!

We recommend changes to the draft PWS that would support market segmentation in outreach.  That is, developers will likely be from different market segments.  Some may be from government agencies that want access to health data for research, some may be private sector medical providers and/or administrators, some may be Veteran Service Organizations (VSO’s), some may be from private sector firms that see innovation opportunities.  

We anticipate that the marketing channels to these different groups would vary.  VA could examine the known pipeline of Lighthouse API’s and/or consider what types of consumers expressed interest to date.  The research requested in this PWS could then focus on one or two specific market segments, resulting in a targeted outreach strategy.

We also recommend considering how to reach development _sponsors_, those individuals who will make the investment decision to commit developer time.

[Sprezzatura](http://www.sprezzmc.com) is a CVE Verified SDVOSB and small business under NAICS 541511.  We would likely respond to a microconsulting RFP.

Thx! Joe Cosentino

**Comment by JCQuin** [comment]
Draft closed.  RFQ posted 6/13/18.
