### ISSUE TITLE
Award of Microconsulting Work Statement - API Landscape Analysis and Near-term Roadmap 36C10B18P2714

### ISSUE THREAD

**Issue by CS-118** [department-of-veterans-affairs/VA-Micropurchase-Repo#19]
## Background

The Lighthouse program is moving VA towards an Application Programming Interface (API) first driven digital enterprise, which will establish the next generation open management platform for Veterans and accelerate transformation in VA's core functions, such as Health, Benefits, Burial and Memorials. This platform will be a system for designing, developing, publishing, operating, monitoring, analyzing, iterating and optimizing VA’s API ecosystem.

## The Play

As the VA Lighthouse Product Owner I have identified two repositories of APIs and publicly available datasets containing information with varying degrees of usefulness to the public. If there are other publicly facing datasets or APIs that would be useful they can be included. I need an evaluation performed to identify and roadmap the five best candidates for public facing APIs.

The two known sources of data are:

Data.gov - https://catalog.data.gov/organization/va-gov and www.va.gov/data

Vets.gov - https://github.com/department-of-veterans-affairs/vets-api

## Deliverable
•Rubric/logical analysis for determining prioritization of APIs
•Detail surrounding how the top five were prioritized based on the rubric/analysis (Not to exceed 2 pages unless approved by the Government)

Deliverables shall be submitted to VA's GitHub Repo.

## Definition of Done

•Submission to VA GitHub
•Refined rubric/analysis agreed to by the vendor and VA
•Accurate application of rubric/analysis

## Time Box

VA anticipates a 2 week iteration to be sufficient. Vendors may propose alternate time frame for VA's consideration.

## Disclaimer

In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information). Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network. Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Purchase Order Clauses

•FAR 52.204-13 System for Award Management Maintenance (OCT 2016)
•FAR 52.227-14 Alternate IV Rights in Data—General (DEC 2007)
•FAR 52.232-33 Payment by Electronic Funds Transfer—System for Award Management (JUL 2013)
•FAR 52.232-39 Unenforceability of Unauthorized Obligations (JUN 2013)
•VAAR 852.232-72 Electronic submission of payment requests. (NOV 2012)

**Comment by JCQuin** [comment]
Deliverables will be placed in this folder: https://github.com/department-of-veterans-affairs/VA-Micropurchase-Repo/tree/master/2018-05-14-API_Landscape_Analysis_and_Near-term_Roadmap
