### ISSUE TITLE
DRAFT - Microconsulting Work Statement – VA Flagship Mobile Application

### ISSUE THREAD

**Issue by CS-118** [department-of-veterans-affairs/VA-Micropurchase-Repo#27]
# DRAFT - Microconsulting Work Statement – VA Flagship Mobile Application

## Background

In the private sector, the majority of large, consumer-facing organizations deliver flagship native iOS and Android mobile applications built on top of their APIs (i.e. Bank of America, Geico, USAA).  As VA builds out its API ecosystem, it is exploring the possibility of creating a flagship mobile application to allow Veterans, Servicemembers, caregivers, and dependents the ability to perform their most common interactions with VA as easily as possible on mobile devices. 

VA currently has a mobile responsive website, Vets.gov, that has a front end built in React and a RESTful API that connects to multiple backend VA systems and provides access to many of the services VA offers. The [front end](https://github.com/department-of-veterans-affairs/vets-website) and [API]( https://github.com/department-of-veterans-affairs/vets-api) code are both open source and may be helpful for understanding what pieces of functionality exist today. 

## The Play

Given Vets.gov, which is already mobile responsive, and its associated JSON APIs as a starting point, what is the best way for VA to deliver the highest quality mobile experience, both quickly and in a way that can be maintained over time?  

Some questions we are seeking answers to include: Should VA build Android and iOS native applications from scratch, and what would the pros and cons of that approach be?  Should VA use primarily webviews, and if so, which applications or pages should not be webviews and why?  Is there a hybrid framework or approach that VA should use, and if so which one and why? How could VA keep native applications and its website in sync as new features are added and content is changed over time?

What is the most common approach in the private sector when creating native mobile applications that are based on an existing responsive website, and what does VA need to do to follow similar best practices?  Where should VA start and what would be defined as a Minimum Viable Product (MVP)?

## Deliverables

- Recommend an approach VA should take towards delivering a high-quality mobile experience, with the reasoning for why this approach is recommended and an explanation of what alternative approaches were considered and why they were not recommended. 
- Document which features of Vets.gov would be the best to implement in a native application, if any, and what the specific benefits are of having those features be native. This could include things like "fingerprint login" or ability to take pictures to submit them as evidence for a claim which could not be easily achieved using webviews or a mobile responsive website. 
- Create a roadmap for both an MVP native application as well as the next highest priority items after an MVP.  What would need to be included in an MVP to have an acceptable product for VA to go to market with?

Deliverables shall be submitted to VA's GitHub Repo.  See VA Micropurchases workflow posted in VA Github.

## Time Box

VA anticipates a 2 week iteration to be sufficient.  It is expected that there will be a kickoff meeting for the vendor to ask questions, then the vendor will present its research and draft deliverables at an intermediate point to incorporate user and Government feedback before submitting its final deliverables. 

Vendors may propose alternate time frame for VA's consideration.

## Disclaimer

In order to avoid potential conflicts of interest, the Contractor will not be provided any non-public information to develop the deliverables. Additionally, all deliverables will be made publicly available in the VA GitHub repository. 

In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information). Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network. Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Evaluation
-  Vendor shall describe how they will complete the deliverables and provide a fixed price for the entire work effort.  VA's micropurchase authority is $10,000 or less.
-  Government will determine which proposal is most beneficial to the Government.
-  Submissions shall be made to the following email addresses by TBD.
	-  Juan.Quinones@va.gov
	-  David.melton@va.gov

## Solicitation Provisions 
-  FAR 52.204-7 System for Award Management (OCT 2016)

## Purchase Order Clauses

- FAR 52.204-13 System for Award Management Maintenance (OCT 2016)
- FAR 52.227-14 Alternate IV Rights in Data—General (DEC 2007)
- FAR 52.232-33 Payment by Electronic Funds Transfer—System for Award Management (JUL 2013)
- FAR 52.232-39 Unenforceability of Unauthorized Obligations (JUN 2013)
- VAAR 852.232-72 Electronic submission of payment requests. (NOV 2012)

**Comment by SurfBigData** [comment]
Hello Juan,

I could not create Pull request back to the master branch of the     department-of-veterans-affairs/VA-Micropurchase-Repo. Only awarded vendor could create pull request?

Regards,
Andrew

**Comment by SurfBigData** [comment]
[VA Flagship Mobile Application Microconsulting and Research-XSI-SBD.docx](https://github.com/department-of-veterans-affairs/VA-Micropurchase-Repo/files/2143555/VA.Flagship.Mobile.Application.Microconsulting.and.Research-XSI-SBD.docx)

**Comment by JCQuin** [comment]
Draft closed. See RFQ at: #33
