### ISSUE TITLE
Sample Doc 1

### ISSUE THREAD

**Issue by koconnor719** [department-of-veterans-affairs/VA-Micropurchase-Repo#44]

**Comment by atamaslen** [comment]
**Project Team X RACI**
The table below defines our team's roles and responsibilities for the following tasks:

- Task 1 - definition 
- Task 2 - definition 

Task Description | PM | Analyst | Engineer
-------------------|-----|---------|----------
Task 1            | A    | R          | I
Task 2            | I    | C          | A

**Comment by koconnor719** [comment]
awesome! perfect. thank you.
