### ISSUE TITLE
DRAFT Microconsulting Work Statement – Micro-Consulting Platform

### ISSUE THREAD

**Issue by JCQuin** [department-of-veterans-affairs/VA-Micropurchase-Repo#50]
## Background

The VA is interested in further pursuing the idea of creating a microconsulting platform and minimum viable product (MVP) for a VA catalog of microconsulting services . Other national governments have launched similar initiatives, such as the Government of Canada’s Talent Cloud. Before embarking on the delivery of a full-blown platform, however, the VA would like to take incremental steps that builds upon the recent success of their first wave of micro-procurements. 

## The Play

That initial step involves engaging industry to produce an MVP Microconsulting Catalog for VA using an online, best practice industry tool (such as GitHub). This Catalog would include information such as which vendors offer microconsulting services, what services they offer, sample deliverables, and how they deliver and price those services.

## Deliverables

Include the following: 

- Scope of Microconsulting Needs 
- Initial Version of a Web-based Microconsulting Catalog and proposed online platform / tool
- VA feedback from potential customers on platform / tool
- Final MVP for the Web-based Microconsulting Catalog 
- Updated Version of the Web-based Microconsulting Catalog with Vendor Information 
- Catalog Listing Instructions for Vendor

## Time Box

VA anticipates a 6 week iteration to be sufficient.     

Vendors may propose alternate time frame for VA's consideration.

## Disclaimer

In order to avoid potential conflicts of interest, the Contractor will not be provided any non-public information to develop the deliverables. Additionally, all deliverables will be made publicly available in the VA GitHub repository. 

In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information). Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network. Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Purchase Order Clauses

- FAR 52.204-13 System for Award Management Maintenance (OCT 2018)
- FAR 52.227-14 Alternate IV Rights in Data—General (DEC 2007)
- FAR 52.232-33 Payment by Electronic Funds Transfer—System for Award Management (OCT 2018)
- FAR 52.232-39 Unenforceability of Unauthorized Obligations (JUN 2013)
- VAAR 852.232-72 Electronic submission of payment requests. (NOV 2018)

**Comment by cscairns** [comment]
@JCQuin @MichaelFrankVA: skylight intends to respond

**Comment by eliotsaylor** [comment]
@JCQuin @MichaelFrankVA Saylor Studios intends to respond, a software development firm in Davis, CA. Currently going through the approval stages from the SBA, as we are in a HUBZone (13cfr126), and that should be our socioeconomic status.

**Comment by ashoknare** [comment]
@JCQuin @MichaelFrankVA Kollabio intends to respond.  We are a minority owned small business under NAICS 541512/$27.5M.

**Comment by RodneyCaswell** [comment]
@JCQuin @MichaelFrankVA Gi4 intends to respond. User-centric, software innovator in Northern Virginia. SAM registered, procurement ready, NAICS 541512 SB, Woman-Owned, SDVOSB, HUBZone certified.

**Comment by Hparagano** [comment]
RFQ posted at https://github.com/department-of-veterans-affairs/VA-Micropurchase-Repo/issues/54
