### ISSUE TITLE
DRAFT Microconsulting Work Statement – DevOps Dashboard and API

### ISSUE THREAD

**Issue by MichaelFrankVA** [department-of-veterans-affairs/VA-Micropurchase-Repo#55]
## Background

As the Department of Veterans Affairs (VA) embraces the culture and practices of a Development Operations (DevOps) environment, the VA OI&T is  focusing on the evolution of several aspects of our organizational process and structure. One way VA is beginning to do this is by migrating toward a Product Line Management (PLM) framework. PLM is a strategic model focused on consolidating systems and projects that share a business strategy, objectives, and customers within a common “product line.” PLM in DevOps will promote coordination between our teams and our stakeholders  , involving business customers, end users, development teams, and operations teams in every step of development and operations from product inception to product sunset.

## The Play

VA Product Line Manager is requiring all development teams   to be able to spin up their DevOps continuous integration (CI) and continuous delivery (CD) environment and deploy code within a matter of minutes and requires a dashboard and an Application Program Interface (API) that provides standardized performance measurement and DevOps maturity metrics across the product line.

## Deliverables

A defined and repeatable strategy/process to create a fully integrated, self-servicing, and expandable DevOps environment that can be managed by a small team of seven to ten members, and contributed to by the open-source and contractor community.

Final Deliverable should be a White Paper / PowerPoint no longer than four pages that outlines:

- Defined Strategy / Process in written and PowerPoint format that details the how-to
- The Strategy / Process should outline how to stand up the Dashboard and identify the API Key Performance Measurements needed to assess DevOps Maturity

Deliverables shall be submitted to VA's GitHub Repo.

## Time Box

VA anticipates a four-week iteration to be sufficient. Draft write-ups should be submitted to VA for approval prior to submission in GitHub.

Vendors may propose alternate time frame for VA's consideration.

## Disclaimer

In order to avoid potential conflicts of interest, the Contractor will not be provided any non-public information to develop the deliverables. Additionally, all deliverable's will be made publicly available in the VA GitHub repository. 

In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information). Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network. Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Purchase Order Clauses

- FAR 52.204-13 System for Award Management Maintenance (OCT 2018)
- FAR 52.227-14 Alternate IV Rights in Data—General (DEC 2007)
- FAR 52.232-33 Payment by Electronic Funds Transfer—System for Award Management (OCT 2018)
- FAR 52.232-39 Unenforceability of Unauthorized Obligations (JUN 2013)
- VAAR 852.232-72 Electronic submission of payment requests. (NOV 2018)

**Comment by RobAWilkinson** [comment]
Oddball intends to respond. We are a service disabled veteran owned small business under NAICS 541512/$30M.

**Comment by MichaelFrankVA** [comment]
Draft Closed. See RFQ at: #60
