### ISSUE TITLE
DRAFT Microconsulting Work Statement – DevOps Best Practices

### ISSUE THREAD

**Issue by MichaelFrankVA** [department-of-veterans-affairs/VA-Micropurchase-Repo#56]
## Background

As the Department of Veterans Affairs (VA) OIT transitions into Development Operations (DevOps), it is imperative that VA and OIT understand the best practices from both the public and private sectors to ensure it is implementing a modern DevOps environment.  VA and OIT need to determine what tools best serve the VA's specific needs, whether they are provided by the government, contractor or a combination of both.

## The Play
The Product Line Manager is seeking a modern DevOps environment.  We need to understand best practices from the private and public sector, specifically around tool selection and integration methods, automation, and identifying the tradeoffs between Government provided tools, contractor provided tools, and a hybrid approach.

## Deliverables

The Vendor shall report on tool selection and integration models based on best practices learned from industry evaluation.

Final Deliverables:
White Paper no longer than 4 pages
Power Point no more than 10 slides

Deliverables shall be submitted to VA's GitHub Repo.

## Time Box

VA anticipates a six to eight week iteration to be sufficient.     

Vendors may propose alternate time frame for VA's consideration.

## Disclaimer

In order to avoid potential conflicts of interest, the Contractor will not be provided any non-public information to develop the deliverables. Additionally, all deliverables will be made publicly available in the VA GitHub repository. 

In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information). Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network. Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Purchase Order Clauses

- FAR 52.204-13 System for Award Management Maintenance (OCT 2018)
- FAR 52.227-14 Alternate IV Rights in Data—General (DEC 2007)
- FAR 52.232-33 Payment by Electronic Funds Transfer—System for Award Management (JUL 2018)
- FAR 52.232-39 Unenforceability of Unauthorized Obligations (JUN 2013)
- VAAR 852.232-72 Electronic submission of payment requests. (NOV 2018)

**Comment by RobAWilkinson** [comment]
Oddball intends to respond. We are a service disabled veteran owned small business under NAICS 541512/$30M.

**Comment by MichaelFrankVA** [comment]
Draft Closed. See RFQ at: #59
