### ISSUE TITLE
DRAFT Microconsulting Work Statement – DevOps Maturity

### ISSUE THREAD

**Issue by MichaelFrankVA** [department-of-veterans-affairs/VA-Micropurchase-Repo#57]
## Background

As the Department of Veterans Affairs (VA) OIT transitions into Development Operations (DevOps), we would benefit from being able to quickly identify maturity levels of all product and project teams.  This ability would help determine best practices for each team to move forward with their processes.

## The Play
The Product Line Manager is seeking the ability to be able to automatically assess the DevOps maturity of each of the product and project teams, along with methods to measure risk to drive DevOps adoption and continuous improvement process.

## Deliverables

The Vendor shall evaluate industry best practices and provide an implementation strategy.

Final Deliverables:
White Paper no longer than four pages
Power Point no longer than 10 slides

Deliverables shall be submitted to VA's GitHub Repo.

## Time Box

VA anticipates a six to eight week iteration to be sufficient.     

Vendors may propose alternate time frame for VA's consideration.

## Disclaimer

In order to avoid potential conflicts of interest, the Contractor will not be provided any non-public information to develop the deliverables. Additionally, all deliverables will be made publicly available in the VA GitHub repository. 

In performance of this effort, the contractor shall not perform a function that requires access to a VA system or VA sensitive information (e.g., system administrator privileged access to a VA system, or contractor systems or processes that utilize VA sensitive information). Additionally, the contractor shall not connect one or more contractor-owned IT devices to a VA internal trusted network. Finally, this acquisition does not involve the storage, generating, transmitting, or exchanging of VA sensitive information.

## Purchase Order Clauses

- FAR 52.204-13 System for Award Management Maintenance (OCT 2018)
- FAR 52.227-14 Alternate IV Rights in Data—General (DEC 2007)
- FAR 52.232-33 Payment by Electronic Funds Transfer—System for Award Management (OCT 2018)
- FAR 52.232-39 Unenforceability of Unauthorized Obligations (JUN 2013)
- VAAR 852.232-72 Electronic submission of payment requests. (NOV 2018)

**Comment by RobAWilkinson** [comment]
Oddball intends to respond. We are a service disabled veteran owned small business under NAICS 541512/$30M.

**Comment by MichaelFrankVA** [comment]
Draft Closed. See RFQ at: #58
